services:
  - type: web
    name: task-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        value: mongodb+srv://ismailkabir170:93gTkpeKRua31j8v@cluster0.obbcewg.mongodb.net/Taskmanager?retryWrites=true&w=majority
      - key: PORT
        value: 5000

  